# Generated by Django 3.1.7 on 2021-03-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherandAuthors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, unique=True)),
                ('publisher', models.BooleanField()),
                ('articles', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userid',
            name='author',
        ),
        migrations.RemoveField(
            model_name='userid',
            name='publisher',
        ),
        migrations.AlterField(
            model_name='userid',
            name='userid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
