# Generated by Django 3.1.7 on 2021-03-04 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210304_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FollowAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userid')),
                ('followingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.authorid')),
            ],
        ),
        migrations.CreateModel(
            name='FollowPublisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userid')),
            ],
        ),
        migrations.CreateModel(
            name='PublisherId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PublisherandAuthors',
        ),
        migrations.AddField(
            model_name='followpublisher',
            name='followingid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publisherid'),
        ),
        migrations.AddField(
            model_name='authorid',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publisherid'),
        ),
    ]
