# Generated by Django 3.1.7 on 2021-03-04 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210304_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorid',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.publisherid'),
        ),
    ]
