# Generated by Django 3.1.7 on 2021-03-05 15:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210304_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleTitle', models.CharField(max_length=220)),
                ('Postedby', models.ForeignKey(on_delete=core.models.AuthorId, to='core.publisherid')),
            ],
        ),
    ]
