# Generated by Django 3.1.7 on 2021-03-05 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='Postedby',
        ),
        migrations.AddField(
            model_name='articles',
            name='Postedbyauthor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.authorid'),
        ),
        migrations.AddField(
            model_name='articles',
            name='Postedbypublisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.publisherid'),
        ),
        migrations.AddField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
